### ISSUE TITLE
Blender 2.8 bone mismatch on export [suggestion]

### ISSUE THREAD

**Issue by Illogicoma** [LagoLunatic/ww_model_helpers#9]
Hi! I just want to highlight an issue I had with blender 2.8+ collada exports that might be worth mentioning in the readme in case anyone else comes across this issue.

I found I had to shrink all the meshes (leaving out the armature) to 1/10th their imported size before exporting, otherwise the skeleton ended up being tiny and causing all kinds of wild animation issues. It's possible this is to do with my units setup, but I was still able to recreate the issue after adjusting them. It was found by enabling skeleton in J3D viewer (the skeleton was tiny).

Thanks for the great work on these tools :)

**Comment by LagoLunatic** [comment]
I haven't experienced anything like this, nor have I ever heard of someone in the discord server having a problem like this.

The most likely explanation is that all of your mesh objects have a 10x scale transform. The correct way to fix this issue is to simply select all the meshes, press Ctrl+A, and select Apply Scale. This will automatically get rid of the mesh object scale and embed it onto the mesh data instead.

If you have any further questions about how to use blender for WW models I recommend joining the WW rando discord server and asking in the cosmetic-mods channel, as there are a number of people there who may help you.
